server:
  port: 8081

spring:
  application:
    name: weather
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: reactive-weather-app
      host: localhost
      port: 27017
  config:
    import: optional:file:.env[.properties]

weather-stack:
  api-url: ${API-URL:https://api.weatherstack.com/current}
  api-key: ${API-KEY:default-key}

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus